// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Albums         string
	Artists        string
	ArtistsAlbums  string
	Comments       string
	Likes          string
	PlaylistTracks string
	Playlists      string
	Roles          string
	Streams        string
	TrackFiles     string
	TrackOwnership string
	Tracks         string
	TracksArtists  string
	Users          string
}{
	Albums:         "albums",
	Artists:        "artists",
	ArtistsAlbums:  "artists_albums",
	Comments:       "comments",
	Likes:          "likes",
	PlaylistTracks: "playlist_tracks",
	Playlists:      "playlists",
	Roles:          "roles",
	Streams:        "streams",
	TrackFiles:     "track_files",
	TrackOwnership: "track_ownership",
	Tracks:         "tracks",
	TracksArtists:  "tracks_artists",
	Users:          "users",
}
