// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Albums", testAlbumsUpsert)

	t.Run("Artists", testArtistsUpsert)

	t.Run("ArtistsAlbums", testArtistsAlbumsUpsert)

	t.Run("Comments", testCommentsUpsert)

	t.Run("Likes", testLikesUpsert)

	t.Run("PlaylistTracks", testPlaylistTracksUpsert)

	t.Run("Playlists", testPlaylistsUpsert)

	t.Run("Roles", testRolesUpsert)

	t.Run("Streams", testStreamsUpsert)

	t.Run("TrackFiles", testTrackFilesUpsert)

	t.Run("TrackOwnerships", testTrackOwnershipsUpsert)

	t.Run("Tracks", testTracksUpsert)

	t.Run("TracksArtists", testTracksArtistsUpsert)

	t.Run("Users", testUsersUpsert)
}
