// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testStreams(t *testing.T) {
	t.Parallel()

	query := Streams()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testStreamsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stream{}
	if err = randomize.Struct(seed, o, streamDBTypes, true, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Streams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStreamsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stream{}
	if err = randomize.Struct(seed, o, streamDBTypes, true, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Streams().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Streams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStreamsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stream{}
	if err = randomize.Struct(seed, o, streamDBTypes, true, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StreamSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Streams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStreamsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stream{}
	if err = randomize.Struct(seed, o, streamDBTypes, true, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := StreamExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Stream exists: %s", err)
	}
	if !e {
		t.Errorf("Expected StreamExists to return true, but got false.")
	}
}

func testStreamsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stream{}
	if err = randomize.Struct(seed, o, streamDBTypes, true, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	streamFound, err := FindStream(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if streamFound == nil {
		t.Error("want a record, got nil")
	}
}

func testStreamsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stream{}
	if err = randomize.Struct(seed, o, streamDBTypes, true, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Streams().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testStreamsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stream{}
	if err = randomize.Struct(seed, o, streamDBTypes, true, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Streams().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testStreamsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	streamOne := &Stream{}
	streamTwo := &Stream{}
	if err = randomize.Struct(seed, streamOne, streamDBTypes, false, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}
	if err = randomize.Struct(seed, streamTwo, streamDBTypes, false, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = streamOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = streamTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Streams().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testStreamsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	streamOne := &Stream{}
	streamTwo := &Stream{}
	if err = randomize.Struct(seed, streamOne, streamDBTypes, false, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}
	if err = randomize.Struct(seed, streamTwo, streamDBTypes, false, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = streamOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = streamTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Streams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func streamBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Stream) error {
	*o = Stream{}
	return nil
}

func streamAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Stream) error {
	*o = Stream{}
	return nil
}

func streamAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Stream) error {
	*o = Stream{}
	return nil
}

func streamBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Stream) error {
	*o = Stream{}
	return nil
}

func streamAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Stream) error {
	*o = Stream{}
	return nil
}

func streamBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Stream) error {
	*o = Stream{}
	return nil
}

func streamAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Stream) error {
	*o = Stream{}
	return nil
}

func streamBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Stream) error {
	*o = Stream{}
	return nil
}

func streamAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Stream) error {
	*o = Stream{}
	return nil
}

func testStreamsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Stream{}
	o := &Stream{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, streamDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Stream object: %s", err)
	}

	AddStreamHook(boil.BeforeInsertHook, streamBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	streamBeforeInsertHooks = []StreamHook{}

	AddStreamHook(boil.AfterInsertHook, streamAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	streamAfterInsertHooks = []StreamHook{}

	AddStreamHook(boil.AfterSelectHook, streamAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	streamAfterSelectHooks = []StreamHook{}

	AddStreamHook(boil.BeforeUpdateHook, streamBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	streamBeforeUpdateHooks = []StreamHook{}

	AddStreamHook(boil.AfterUpdateHook, streamAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	streamAfterUpdateHooks = []StreamHook{}

	AddStreamHook(boil.BeforeDeleteHook, streamBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	streamBeforeDeleteHooks = []StreamHook{}

	AddStreamHook(boil.AfterDeleteHook, streamAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	streamAfterDeleteHooks = []StreamHook{}

	AddStreamHook(boil.BeforeUpsertHook, streamBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	streamBeforeUpsertHooks = []StreamHook{}

	AddStreamHook(boil.AfterUpsertHook, streamAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	streamAfterUpsertHooks = []StreamHook{}
}

func testStreamsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stream{}
	if err = randomize.Struct(seed, o, streamDBTypes, true, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Streams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStreamsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stream{}
	if err = randomize.Struct(seed, o, streamDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(streamPrimaryKeyColumns, streamColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := Streams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStreamToOneTrackUsingTrack(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Stream
	var foreign Track

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, streamDBTypes, false, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, trackDBTypes, false, trackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Track struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.TrackID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Track().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddTrackHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Track) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := StreamSlice{&local}
	if err = local.L.LoadTrack(ctx, tx, false, (*[]*Stream)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Track == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Track = nil
	if err = local.L.LoadTrack(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Track == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testStreamToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Stream
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, streamDBTypes, true, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.UserID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := StreamSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*Stream)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testStreamToOneSetOpTrackUsingTrack(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Stream
	var b, c Track

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, streamDBTypes, false, strmangle.SetComplement(streamPrimaryKeyColumns, streamColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, trackDBTypes, false, strmangle.SetComplement(trackPrimaryKeyColumns, trackColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, trackDBTypes, false, strmangle.SetComplement(trackPrimaryKeyColumns, trackColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Track{&b, &c} {
		err = a.SetTrack(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Track != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Streams[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TrackID != x.ID {
			t.Error("foreign key was wrong value", a.TrackID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TrackID))
		reflect.Indirect(reflect.ValueOf(&a.TrackID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TrackID != x.ID {
			t.Error("foreign key was wrong value", a.TrackID, x.ID)
		}
	}
}
func testStreamToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Stream
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, streamDBTypes, false, strmangle.SetComplement(streamPrimaryKeyColumns, streamColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Streams[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.UserID, x.ID) {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.UserID, x.ID) {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testStreamToOneRemoveOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Stream
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, streamDBTypes, false, strmangle.SetComplement(streamPrimaryKeyColumns, streamColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetUser(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveUser(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.User().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.User != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.UserID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.Streams) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testStreamsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stream{}
	if err = randomize.Struct(seed, o, streamDBTypes, true, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStreamsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stream{}
	if err = randomize.Struct(seed, o, streamDBTypes, true, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StreamSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStreamsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stream{}
	if err = randomize.Struct(seed, o, streamDBTypes, true, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Streams().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	streamDBTypes = map[string]string{`ID`: `bigint`, `UserID`: `bigint`, `TrackID`: `bigint`, `StartedAt`: `timestamp with time zone`, `DurationListened`: `integer`, `Device`: `text`, `IP`: `inet`, `UserAgent`: `text`, `IsCompleted`: `boolean`, `CreatedAt`: `timestamp with time zone`}
	_             = bytes.MinRead
)

func testStreamsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(streamPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(streamAllColumns) == len(streamPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Stream{}
	if err = randomize.Struct(seed, o, streamDBTypes, true, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Streams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, streamDBTypes, true, streamPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testStreamsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(streamAllColumns) == len(streamPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Stream{}
	if err = randomize.Struct(seed, o, streamDBTypes, true, streamColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Streams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, streamDBTypes, true, streamPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(streamAllColumns, streamPrimaryKeyColumns) {
		fields = streamAllColumns
	} else {
		fields = strmangle.SetComplement(
			streamAllColumns,
			streamPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := StreamSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testStreamsUpsert(t *testing.T) {
	t.Parallel()

	if len(streamAllColumns) == len(streamPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Stream{}
	if err = randomize.Struct(seed, &o, streamDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Stream: %s", err)
	}

	count, err := Streams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, streamDBTypes, false, streamPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Stream struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Stream: %s", err)
	}

	count, err = Streams().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
