// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testTrackFiles(t *testing.T) {
	t.Parallel()

	query := TrackFiles()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testTrackFilesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackFile{}
	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TrackFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTrackFilesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackFile{}
	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := TrackFiles().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TrackFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTrackFilesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackFile{}
	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TrackFileSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TrackFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTrackFilesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackFile{}
	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := TrackFileExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if TrackFile exists: %s", err)
	}
	if !e {
		t.Errorf("Expected TrackFileExists to return true, but got false.")
	}
}

func testTrackFilesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackFile{}
	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	trackFileFound, err := FindTrackFile(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if trackFileFound == nil {
		t.Error("want a record, got nil")
	}
}

func testTrackFilesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackFile{}
	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = TrackFiles().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testTrackFilesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackFile{}
	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := TrackFiles().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTrackFilesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	trackFileOne := &TrackFile{}
	trackFileTwo := &TrackFile{}
	if err = randomize.Struct(seed, trackFileOne, trackFileDBTypes, false, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}
	if err = randomize.Struct(seed, trackFileTwo, trackFileDBTypes, false, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = trackFileOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = trackFileTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TrackFiles().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTrackFilesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	trackFileOne := &TrackFile{}
	trackFileTwo := &TrackFile{}
	if err = randomize.Struct(seed, trackFileOne, trackFileDBTypes, false, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}
	if err = randomize.Struct(seed, trackFileTwo, trackFileDBTypes, false, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = trackFileOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = trackFileTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TrackFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func trackFileBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *TrackFile) error {
	*o = TrackFile{}
	return nil
}

func trackFileAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *TrackFile) error {
	*o = TrackFile{}
	return nil
}

func trackFileAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *TrackFile) error {
	*o = TrackFile{}
	return nil
}

func trackFileBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *TrackFile) error {
	*o = TrackFile{}
	return nil
}

func trackFileAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *TrackFile) error {
	*o = TrackFile{}
	return nil
}

func trackFileBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *TrackFile) error {
	*o = TrackFile{}
	return nil
}

func trackFileAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *TrackFile) error {
	*o = TrackFile{}
	return nil
}

func trackFileBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *TrackFile) error {
	*o = TrackFile{}
	return nil
}

func trackFileAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *TrackFile) error {
	*o = TrackFile{}
	return nil
}

func testTrackFilesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &TrackFile{}
	o := &TrackFile{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, trackFileDBTypes, false); err != nil {
		t.Errorf("Unable to randomize TrackFile object: %s", err)
	}

	AddTrackFileHook(boil.BeforeInsertHook, trackFileBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	trackFileBeforeInsertHooks = []TrackFileHook{}

	AddTrackFileHook(boil.AfterInsertHook, trackFileAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	trackFileAfterInsertHooks = []TrackFileHook{}

	AddTrackFileHook(boil.AfterSelectHook, trackFileAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	trackFileAfterSelectHooks = []TrackFileHook{}

	AddTrackFileHook(boil.BeforeUpdateHook, trackFileBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	trackFileBeforeUpdateHooks = []TrackFileHook{}

	AddTrackFileHook(boil.AfterUpdateHook, trackFileAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	trackFileAfterUpdateHooks = []TrackFileHook{}

	AddTrackFileHook(boil.BeforeDeleteHook, trackFileBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	trackFileBeforeDeleteHooks = []TrackFileHook{}

	AddTrackFileHook(boil.AfterDeleteHook, trackFileAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	trackFileAfterDeleteHooks = []TrackFileHook{}

	AddTrackFileHook(boil.BeforeUpsertHook, trackFileBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	trackFileBeforeUpsertHooks = []TrackFileHook{}

	AddTrackFileHook(boil.AfterUpsertHook, trackFileAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	trackFileAfterUpsertHooks = []TrackFileHook{}
}

func testTrackFilesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackFile{}
	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TrackFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTrackFilesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackFile{}
	if err = randomize.Struct(seed, o, trackFileDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(trackFilePrimaryKeyColumns, trackFileColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := TrackFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTrackFileToOneTrackUsingTrack(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local TrackFile
	var foreign Track

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, trackFileDBTypes, true, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, trackDBTypes, false, trackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Track struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.TrackID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Track().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddTrackHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Track) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := TrackFileSlice{&local}
	if err = local.L.LoadTrack(ctx, tx, false, (*[]*TrackFile)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Track == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Track = nil
	if err = local.L.LoadTrack(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Track == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testTrackFileToOneSetOpTrackUsingTrack(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TrackFile
	var b, c Track

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, trackFileDBTypes, false, strmangle.SetComplement(trackFilePrimaryKeyColumns, trackFileColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, trackDBTypes, false, strmangle.SetComplement(trackPrimaryKeyColumns, trackColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, trackDBTypes, false, strmangle.SetComplement(trackPrimaryKeyColumns, trackColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Track{&b, &c} {
		err = a.SetTrack(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Track != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.TrackFiles[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.TrackID, x.ID) {
			t.Error("foreign key was wrong value", a.TrackID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TrackID))
		reflect.Indirect(reflect.ValueOf(&a.TrackID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.TrackID, x.ID) {
			t.Error("foreign key was wrong value", a.TrackID, x.ID)
		}
	}
}

func testTrackFileToOneRemoveOpTrackUsingTrack(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TrackFile
	var b Track

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, trackFileDBTypes, false, strmangle.SetComplement(trackFilePrimaryKeyColumns, trackFileColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, trackDBTypes, false, strmangle.SetComplement(trackPrimaryKeyColumns, trackColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetTrack(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveTrack(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Track().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Track != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.TrackID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.TrackFiles) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testTrackFilesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackFile{}
	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTrackFilesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackFile{}
	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TrackFileSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTrackFilesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TrackFile{}
	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TrackFiles().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	trackFileDBTypes = map[string]string{`ID`: `bigint`, `TrackID`: `bigint`, `StorageURL`: `text`, `Format`: `text`, `Bitrate`: `integer`, `SizeBytes`: `bigint`, `Status`: `smallint`, `UploadedAt`: `timestamp with time zone`}
	_                = bytes.MinRead
)

func testTrackFilesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(trackFilePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(trackFileAllColumns) == len(trackFilePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TrackFile{}
	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TrackFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFilePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testTrackFilesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(trackFileAllColumns) == len(trackFilePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TrackFile{}
	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFileColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TrackFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, trackFileDBTypes, true, trackFilePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(trackFileAllColumns, trackFilePrimaryKeyColumns) {
		fields = trackFileAllColumns
	} else {
		fields = strmangle.SetComplement(
			trackFileAllColumns,
			trackFilePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := TrackFileSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testTrackFilesUpsert(t *testing.T) {
	t.Parallel()

	if len(trackFileAllColumns) == len(trackFilePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := TrackFile{}
	if err = randomize.Struct(seed, &o, trackFileDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TrackFile: %s", err)
	}

	count, err := TrackFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, trackFileDBTypes, false, trackFilePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TrackFile struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TrackFile: %s", err)
	}

	count, err = TrackFiles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
